fiberplane/fp

CHANGELOG.md
Cargo.lock
src/views.rs

uses some funky new clap features `value_parser = .range` and `requires` which we haven't used before but should 🎉

add support for views v2

---

CHANGELOG.md
Cargo.lock
src/providers.rs

See also: https://github.com/fiberplane/fiberplane/pull/18
Resolves: FP-2705

Remove support for the legacy protocol

---

.github/ISSUE_TEMPLATE/01_issue.yml
.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Adds an issue template similar to https://github.com/fiberplane/fiberplane/pull/22
Resolves: FP-1491
- ~~[ ] Update CHANGELOG.md~~

Add issue template

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version to 2.7.0

---

src/main.rs

Add more aliases to DataSources command

---

.github/workflows/release.yml
CHANGELOG.md

Fix publishing docs to ReadMe

---

CHANGELOG.md
Cargo.lock
src/interactive.rs
src/notebooks.rs
src/views.rs

studio wanted it so fp gets it as well :)

add sorting to notebook search command

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/main.rs
src/utils.rs
src/views.rs

related https://github.com/fiberplane/fiberplane/pull/31
Resolves FP-3079

allow clearing optional view fields

---

Cargo.lock
Cargo.toml

Upgrades to fp-bindgen v3.0.0: https://github.com/fiberplane/fp-bindgen/pull/193
See also: https://github.com/fiberplane/fiberplane/pull/52

Upgrade to fp-bindgen v3.0.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/interactive.rs
src/main.rs
src/webhooks.rs

Webhooks!!

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/webhooks.rs

fixes FP-3201
fixes FP-3200
related: https://github.com/fiberplane/fiberplane/pull/54

extend webhook cli with new things specified in design

---

.github/workflows/release.yml

Fix an oopsie in workflow
~~[ ] Update CHANGELOG.md~~

Fix linux/arm64 build

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/release_install_script.yml
Cargo.lock
Cargo.toml

- Bump the version to 2.10.0, which will be the next version.
- Trigger builds when the release is created.
- Use the newer method for configuring AWS credentials
- ~~[ ] Update CHANGELOG.md~~

Bump version and update workflows

---

CHANGELOG.md
src/auth.rs

Resolves FP-3225
needs to be merged after https://github.com/fiberplane/monofiber/pull/27/ has been merged

redirect to studio sign in page on `fp login`

---

CHANGELOG.md
src/auth.rs
src/config.rs
src/daemons.rs
src/data_sources.rs
src/events.rs
src/experiments.rs
src/labels.rs
src/main.rs
src/notebooks.rs
src/run/mod.rs
src/shell/mod.rs
src/snippets.rs
src/templates.rs
src/tokens.rs
src/triggers.rs
src/users.rs
src/views.rs
src/webhooks.rs
src/workspaces.rs

Allow overriding of the token through a arg

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Prepare 2.16.0 release

---

.github/workflows/build.yml
.github/workflows/release.yml

Update GitHub actions

---

Cargo.lock
Cargo.toml
src/update.rs

point away from `fiberplane` git repo

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Versions weren't bumped after the previous release, so here we go.

Bump versions to prepare for the release

---

Cargo.lock
Cargo.toml
src/auth.rs
src/config.rs
src/experiments.rs

Update to reqwest 0.12

---

.github/workflows/audit_rust.yml
Cargo.lock
deny.toml

- **Add deny.toml and cargo deny action**
- **cargo update**

Refactor cargo-check action to cargo-deny

---

.cargo/config.toml
Cargo.lock

- **Update yanked crates**
- **Remove artifactory registry**

Update pest crates

---

CHANGELOG.md
src/auth.rs
src/config.rs
src/daemons.rs
src/data_sources.rs
src/events.rs
src/experiments.rs
src/front_matter.rs
src/integrations.rs
src/integrations/pagerduty_receivers.rs
src/labels.rs
src/main.rs
src/notebooks.rs
src/profiles.rs
src/run/mod.rs
src/shell/mod.rs
src/snippets.rs
src/templates.rs
src/tokens.rs
src/triggers.rs
src/users.rs
src/views.rs
src/webhooks.rs
src/workspaces.rs

allows you to have arbritary amount of profiles with different `base_url`s and authentication `token`s.
```shell
[mari@dell-stupid-mattress fp]$ fp profiles list
List of profiles:
- default (default)
- dev
- demo
[mari@dell-stupid-mattress fp]$ fp workspaces list
ID                      Name               Type          Default Data Sources                               Created at                   Updated at                  
0li9_5B8Sq2fPg7oLfZ5nw  fiberplane         Organization  elasticsearch, https, prometheus=proxy-production  2022-11-14T15:23:25.777867Z  2023-05-19T12:54:15.043263Z 
wTTZcPV5Q8qqQ-340fAEWQ  issue-lab          Organization  prometheus=ivan-test                               2022-11-23T10:24:44.36792Z   2023-05-19T12:44:00.194614Z 
VZBuD3DJRAqaFtYfxb9eYQ …
```

`fp profiles`

---

.github/dependabot.yml

dont update to majors for cargo dependencies

---

.github/workflows/weekly_dependency_update.yml

assign the team to dependabot updates

---

.github/workflows/weekly_dependency_update.yml

match dependabot actor instead of branch names

---

.github/workflows/weekly_dependency_update.yml

follows the error message solution provided in https://github.com/fiberplane/fp/actions/runs/9447011872/job/26017891622

use `gh` suggested env in weekly dependabot reviewer action

---

Cargo.lock
deny.toml
src/shell/text_renderer.rs

Resolve cargo-deny issues and clippies
